name: build-book

# Only run this when the push is NOT to the main branch
on:
  push:
    branches-ignore:
    - main

# This job installs dependencies and builds the book
jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
